// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DFC.App.ExploreCareers.UI.FunctionalTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ExploreCareersCUILinksFeature : object, Xunit.IClassFixture<ExploreCareersCUILinksFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ExploreCareersCUILinks.feature"
#line hidden
        
        public ExploreCareersCUILinksFeature(ExploreCareersCUILinksFeature.FixtureData fixtureData, DFC_App_ExploreCareers_UI_FunctionalTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "Features", "ExploreCareersCUILinks", "\tAs a citizen on the National Careers website \r\n\tI want to be sure that links wor" +
                    "k fine", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        public virtual void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked(string jobCategory, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Job category", jobCategory);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TCC01 - Job profiles links and breadcrumb verified on being clicked", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given(string.Format("I am at the \"Job categories\" web page for {0}", jobCategory), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.When("I click the link for each of the Job profiles listed thereunder in turn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
 testRunner.Then("I am navigated to the Job profiles page for the Job profile clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 10
 testRunner.And("the breadcrumb for that specific Job profile is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Administrati" +
            "on")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Administrati" +
            "on")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_Administration()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Administration", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Animal care")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Animal care")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_AnimalCare()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Animal care", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Beauty and w" +
            "ellbeing")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Beauty and w" +
            "ellbeing")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_BeautyAndWellbeing()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Beauty and wellbeing", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Business and" +
            " finance")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Business and" +
            " finance")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_BusinessAndFinance()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Business and finance", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Computing, t" +
            "echnology and digital")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Computing, t" +
            "echnology and digital")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_ComputingTechnologyAndDigital()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Computing, technology and digital", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Construction" +
            " and trades")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Construction" +
            " and trades")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_ConstructionAndTrades()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Construction and trades", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Creative and" +
            " media")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Creative and" +
            " media")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_CreativeAndMedia()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Creative and media", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Delivery and" +
            " storage")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Delivery and" +
            " storage")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_DeliveryAndStorage()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Delivery and storage", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Emergency an" +
            "d uniform services")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Emergency an" +
            "d uniform services")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_EmergencyAndUniformServices()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Emergency and uniform services", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Engineering " +
            "and maintenance")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Engineering " +
            "and maintenance")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_EngineeringAndMaintenance()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Engineering and maintenance", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Environment " +
            "and land")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Environment " +
            "and land")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_EnvironmentAndLand()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Environment and land", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Government s" +
            "ervices")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Government s" +
            "ervices")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_GovernmentServices()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Government services", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Healthcare")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Healthcare")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_Healthcare()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Healthcare", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Home service" +
            "s")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Home service" +
            "s")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_HomeServices()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Home services", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Hospitality " +
            "and food")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Hospitality " +
            "and food")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_HospitalityAndFood()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Hospitality and food", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Law and lega" +
            "l")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Law and lega" +
            "l")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_LawAndLegal()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Law and legal", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Managerial")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Managerial")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_Managerial()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Managerial", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Manufacturin" +
            "g")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Manufacturin" +
            "g")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_Manufacturing()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Manufacturing", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Retail and s" +
            "ales")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Retail and s" +
            "ales")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_RetailAndSales()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Retail and sales", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Science and " +
            "research")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Science and " +
            "research")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_ScienceAndResearch()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Science and research", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Social care")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Social care")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_SocialCare()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Social care", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Sports and l" +
            "eisure")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Sports and l" +
            "eisure")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_SportsAndLeisure()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Sports and leisure", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Teaching and" +
            " education")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Teaching and" +
            " education")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_TeachingAndEducation()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Teaching and education", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Transport")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Transport")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_Transport()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Transport", ((string[])(null)));
#line hidden
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TCC01 - Job profiles links and breadcrumb verified on being clicked: Travel and t" +
            "ourism")]
        [Xunit.TraitAttribute("FeatureTitle", "ExploreCareersCUILinks")]
        [Xunit.TraitAttribute("Description", "TCC01 - Job profiles links and breadcrumb verified on being clicked: Travel and t" +
            "ourism")]
        public void TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked_TravelAndTourism()
        {
#line 6
this.TCC01_JobProfilesLinksAndBreadcrumbVerifiedOnBeingClicked("Travel and tourism", ((string[])(null)));
#line hidden
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ExploreCareersCUILinksFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ExploreCareersCUILinksFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
