variables:
- name: ResourceGroup
  value: $(ResourcePrefix)-rg
- name: AppServiceName
  value: $(ResourcePrefix)-as
- name: EnableAzureMonitorAlerting
  value: true
- name: cosmosDatabaseName
  value: dfc-app-explorecareers
- name: cosmosContainerName
  value: job-categories
- name: cosmosThroughput
  value: 400
- name: jobProfileBaseAddress
  value: $(jobProfileSearchAddress)/
- name: subscriptionEndpoint
  value: https://$(AppServiceName).$(appServiceDomain)/api/webhook/ReceiveEvents
- name: autoCompleteEndpoint
  value: $(jobCategoryBaseAddress)searchautocomplete
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: apiName
  value: explorecareers
- name: apiId
  value: composite-ui-explorecareers
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)