variables:
- name: ResourceGroup
  value: $(ResourcePrefix)-rg
- name: AppServiceName
  value: $(ResourcePrefix)-as
- name: EnableAzureMonitorAlerting
  value: true
- name: cosmosDatabaseName
  value: dfc-app-explorecareers
- name: cosmosContainerName
  value: job-categories
- name: cosmosThroughput
  value: 400
- name: jobProfileBaseAddress
  value: $(jobProfileSearchAddress)/
- name: subscriptionEndpoint
  value: $(AppServiceName).$(appServiceDomain)/api/webhook/ReceiveEvents
- name: subscriptionServiceEndpoint
  value: $(ApimProxyAddress)/composite-ui/subscription/api/Execute/
- name: autoCompleteEndpoint
  value: $(jobCategoryBaseAddress)searchautocomplete
- name: contentUrl
  value: $(ContentApiAddress)/api/execute