variables:
- name: ResourceGroup
  value: $(ResourcePrefix)-rg
- name: AppServiceName
  value: $(ResourcePrefix)-as
- name: EnableAzureMonitorAlerting
  value: true
- name: jobProfileBaseAddress
  value: $(jobProfileSearchAddress)/
- name: autoCompleteEndpoint
  value: $(jobCategoryBaseAddress)searchautocomplete
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: apiName
  value: explorecareers
- name: apiId
  value: composite-ui-explorecareers
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/explorecareers
- name: bingSpellCheckApiUrl
  value: https://api.cognitive.microsoft.com/bing/v7.0/spellcheck/
- name: RedisCacheEnabled
  value: true
- name: RedisCacheExpiryInSeconds
  value: 43200