variables:
  - name: ReleaseEnvironmentName
    value: DEV
  - name: ResourcePrefix
    value: dfc-dev-app-explorecareers
  - name: subscriptionServiceEndpoint
    value: https://dfc-dev-api-eventgridsubscriptions-fa.$(appServiceDomain)
  - name: loggingLogLevelDefault
    value: Trace
  - name: ContentMode
    value: PUBLISHED