variables:
- name: ReleaseEnvironmentName
  value: PP
- name: ResourcePrefix
  value: dfc-pp-app-explorecareers
- name: aspTier
  value: Standard
- name: aspInstances
  value: 4
- name: aspSize
  value: 1
- name: subscriptionServiceEndpoint
  value: https://dfc-pp-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: loggingLogLevelDefault
  value: Warning
- name: contentMode
  value: PUBLISHED