variables:
- name: ReleaseEnvironmentName
  value: PRD
- name: ResourcePrefix
  value: dfc-prd-app-explorecareers
- name: subscriptionServiceEndpoint
  value: https://dfc-prd-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: loggingLogLevelDefault
  value: Warning
- name: ContentMode
  value: PUBLISHED
- name: Expiry
  value: 4