variables:
- name: ReleaseEnvironmentName
  value: SIT
- name: ResourcePrefix
  value: dfc-sit-app-explorecareers
- name: subscriptionServiceEndpoint
  value: https://dfc-sit-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: loggingLogLevelDefault
  value: Trace
- name: ContentMode
  value: PUBLISHED
- name: Expiry
  value: 4