variables:
- name: ReleaseEnvironmentName
  value: SIT
- name: ResourcePrefix
  value: dfc-sit-app-explorecareers
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: subscriptionServiceEndpoint
  value: https://dfc-sit-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: loggingLogLevelDefault
  value: Trace